
# ###########################
# # AUGMENTATION SETTINGS # # 
# ###########################

# LIST OF ALLOWED EFFECTS AND BOUNDS

live_effects:
  overdrive:  
    gain: 
      upper: 10
      lower: 80
    colour:
      upper: 20
      lower: 0
  reverb: 
    reverberance:
      upper: 0
      lower: 100
    hf_damping: 50
    pre_delay: 20
    reverberance: 50
    room_scale: 100
    stereo_depth: 100
    wet_gain: 0
    wet_only: false
  delay:
    decays:
    - 0.3 
    - 0.25
    delays: 
    - 1000 
    - 1800
    gain_in: 0.8
    gain_out: 0.5
    parallel: false


# ALLOW RANDOMIZATON BETWEEN THESE EFFECTS
##########################################

# If bounds not provided, use defaults as lower

randomize:
  colour:
  - 'gain'
  - 'colour'

# DISALLOW MODIFICATION
#######################

blacklist:
  delay:
  - 'all' # Don't alter any

